version: "3.7"
services:
  jobs:
    image: $IMAGE_ID:$VERSION
    working_dir: /app/
    volumes:
      - $DIRECTORY_APPLICATION/uploads:/app/uploads
      - $DIRECTORY_APPLICATION/logs:/app/application/logs
      - $DIRECTORY_APPLICATION/temp:/app/temp
    depends_on:
      - db
      - redis
      - app
    environment:
      - ENVIRONMENT=production
      - DB_HOST=db
      - DB_NAME=erpjb
      - DB_PASSWORD=erpjb@2020
      - DB_USER=root
      - BANK_INTER_PDF_FILES=temp/
      - DISCORD_EXCEPTIONS=https://discord.com/api/webhooks/783155960201347072/TN1yr1WndAI9Ug9vuDxb_qUQOnERJ8qs_XmzUOwYLUM35pRDdE5CJl3qfxxSjezIEZQh
      - DISCORD_HOOK=https://discord.com/api/webhooks/783101033672605698/d61CeThzLZcUHI_N7NBcIM1qTEF6HLgNw7gO8CAqhKVmuy_6BEHAMUW1nbEYOgev6Nyu
      - BASE_URL=https://erpjb.com.br
      - LICENSE_APP=63AH2N-XTFFLP-952QAM-UTBUai9NL0Q5R2lLeE4xbXZBMGVMVnEwMlpvTTU0QmNFcml6emVLNkk0MD0=
    tty: true
    networks:
      - app_net
      - redis_net
      - database_net
    command: [
      "/app/schedule-run.sh"
    ] 
  app:
    image: $IMAGE_ID:$VERSION
    environment:
      - ENVIRONMENT=production
      - DB_HOST=db
      - DB_NAME=erpjb
      - DB_PASSWORD=erpjb@2020
      - DB_USER=root
      - BANK_INTER_PDF_FILES=temp/
      - DISCORD_EXCEPTIONS=https://discord.com/api/webhooks/783155960201347072/TN1yr1WndAI9Ug9vuDxb_qUQOnERJ8qs_XmzUOwYLUM35pRDdE5CJl3qfxxSjezIEZQh
      - DISCORD_HOOK=https://discord.com/api/webhooks/783101033672605698/d61CeThzLZcUHI_N7NBcIM1qTEF6HLgNw7gO8CAqhKVmuy_6BEHAMUW1nbEYOgev6Nyu
      - BASE_URL=https://erpjb.com.br
      - LICENSE_APP=63AH2N-XTFFLP-952QAM-UTBUai9NL0Q5R2lLeE4xbXZBMGVMVnEwMlpvTTU0QmNFcml6emVLNkk0MD0=
    volumes:
      - $DIRECTORY_APPLICATION/uploads:/app/uploads
      - $DIRECTORY_APPLICATION/logs:/app/application/logs
      - $DIRECTORY_APPLICATION/temp:/app/temp
    deploy:
      labels:
        traefik.http.services.erp-production.loadbalancer.server.port: "80"
        traefik.http.routers.erp-production.rule: (Host(`eeividadecrianca.com.br`) || Host(`www.eeividadecrianca.com.br`))
        traefik.docker.network: proxy
        traefik.enable: "true"
        traefik.http.routers.erp-production.entrypoints: http
        traefik.http.routers.erp-production-secure.entrypoints: https
        traefik.http.routers.erp-production-secure.rule: Host(`eeividadecrianca.com.br`)
        traefik.http.routers.erp-production-secure.tls: "true"
        traefik.http.routers.erp-production-secure.tls.certresolver: le
        traefik.http.middlewares.erp-production_redirect.redirectscheme.scheme: https
        traefik.http.routers.erp-production.middlewares: "erp-production_redirect"
    tty: true
    networks:
      - proxy
      - app_net
      - redis_net
      - database_net
networks:
  proxy:
    external: true
  redis_net:
    external: true
  database_net:
    external: true     
  app_net:

configs:
   mysql.conf:
     file: './mysql.conf'  