version: "3.7"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: erpjb
      MYSQL_PASSWORD: erpjb@2020
      MYSQL_ROOT_PASSWORD: erpjb@2020
      MYSQL_USER: erpjp
    command: 
      [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
      
    volumes:
      - /var/apps/erpjb/production/database/msyql:/var/lib/mysql
    networks:
     - app_net
    configs:
      -
        source: mysql.conf
        target: /etc/mysql/conf.d/group.cnf 
  jobs:
    image: carlosocarvalho/erpjb-school:main
    working_dir: /app/
    volumes:
      - /var/apps/erpjb/production/app/uploads:/app/uploads
      - /var/apps/erpjb/production/app/logs:/app/application/logs
      - /var/apps/erpjb/production/app/temp:/app/temp
    depends_on:
      - db
      - redis
      - app
    environment:
      - ENVIRONMENT=production
      - DB_HOST=db
      - DB_NAME=erpjb
      - DB_PASSWORD=erpjb@2020
      - DB_USER=root
      - BANK_INTER_PDF_FILES=temp/
      - DISCORD_EXCEPTIONS=https://discord.com/api/webhooks/783155960201347072/TN1yr1WndAI9Ug9vuDxb_qUQOnERJ8qs_XmzUOwYLUM35pRDdE5CJl3qfxxSjezIEZQh
      - DISCORD_HOOK=https://discord.com/api/webhooks/783101033672605698/d61CeThzLZcUHI_N7NBcIM1qTEF6HLgNw7gO8CAqhKVmuy_6BEHAMUW1nbEYOgev6Nyu
      - BASE_URL=https://erpjb.com.br
      - LICENSE_APP=63AH2N-XTFFLP-952QAM-UTBUai9NL0Q5R2lLeE4xbXZBMGVMVnEwMlpvTTU0QmNFcml6emVLNkk0MD0=
    tty: true
    networks:
      - app_net
      - redis_net
    command: [
      "/usr/local/bin/php /app/man migrate -n",
      "/app/schedule-run.sh"
    ] 
  app:
    image: carlosocarvalho/erpjb-school:main
    environment:
      - ENVIRONMENT=production
      - DB_HOST=db
      - DB_NAME=erpjb
      - DB_PASSWORD=erpjb@2020
      - DB_USER=root
      - BANK_INTER_PDF_FILES=temp/
      - DISCORD_EXCEPTIONS=https://discord.com/api/webhooks/783155960201347072/TN1yr1WndAI9Ug9vuDxb_qUQOnERJ8qs_XmzUOwYLUM35pRDdE5CJl3qfxxSjezIEZQh
      - DISCORD_HOOK=https://discord.com/api/webhooks/783101033672605698/d61CeThzLZcUHI_N7NBcIM1qTEF6HLgNw7gO8CAqhKVmuy_6BEHAMUW1nbEYOgev6Nyu
      - BASE_URL=https://erpjb.com.br
      - LICENSE_APP=63AH2N-XTFFLP-952QAM-UTBUai9NL0Q5R2lLeE4xbXZBMGVMVnEwMlpvTTU0QmNFcml6emVLNkk0MD0=
    volumes:
      - /var/apps/erpjb/production/app/uploads:/app/uploads
      - /var/apps/erpjb/production/app/logs:/app/application/logs
      - /var/apps/erpjb/production/app/temp:/app/temp
    
    deploy:
      labels:
        traefik.http.services.erpjpb-production.loadbalancer.server.port: "80"
        traefik.http.routers.erpjpb-production.rule: (Host(`erpjb.com.br`))
        traefik.docker.network: proxy
        traefik.enable: "true"
        traefik.http.routers.erpjpb-production.entrypoints: http
        traefik.http.routers.erpjpb-production-secure.entrypoints: https
        traefik.http.routers.erpjpb-production-secure.rule: Host(`erpjb.com.br`)
        traefik.http.routers.erpjpb-production-secure.tls: "true"
        traefik.http.routers.erpjpb-production-secure.tls.certresolver: le
        traefik.http.middlewares.erpjpb-production_redirect.redirectscheme.scheme: https
        traefik.http.routers.erpjpb-production.middlewares: "erpjpb-production_redirect"
    tty: true
    networks:
      - proxy
      - app_net
      - redis_net
networks:
  proxy:
    external: true
  redis_net:
    external: true  
  app_net:

configs:
   mysql.conf:
     file: './mysql.conf'  