version: "3.7"
services:
  redis:
    image: redis:latest
    networks:
      - erp_net  
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: erp
      MYSQL_PASSWORD: erp
      MYSQL_ROOT_PASSWORD: erp
      MYSQL_USER: erp
    command: 
      [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
        
      ]
    volumes:
      - ./data:/var/lib/mysql
    networks:
     - erp_net
    ports:
     - 3307:3306
    configs:
      -
        source: mysql.conf
        target: /etc/mysql/conf.d/group.cnf
  app:
    image: webdevops/php-nginx:7.3
    environment:
      - VERSION_erp=1.0.2
      - PHP_DATE_TIMEZONE=America/Sao_Paulo
      - LICENSE_APP=63AH2N-XTFFLP-952QAM-UTBUai9NL0Q5R2lLeE4xbXZBMGVMVnEwMlpvTTU0QmNFcml6emVLNkk0MD0=
    volumes:
     - ./:/app/
    # configs:
    #   - 
    #     source: erp_conf
    #     target: /opt/docker/etc/httpd/conf.d/erp.conf
    #   -
    #     source: php.ini
    #     target: /opt/docker/etc/php/php.ini
    #   -
    #     source: periodico.conf
    #     target: /opt/docker/etc/supervisor.d/erp.conf   

    deploy:
      labels:
        traefik.http.services.erp.loadbalancer.server.port: "80"
        traefik.http.routers.erp.rule: (Host(`erp.dev.in`) )
        traefik.docker.network: proxy
        traefik.enable: "true"
        traefik.http.routers.erp.entrypoints: http
        traefik.http.routers.erp-secure.entrypoints: https
        traefik.http.routers.erp-secure.rule: (Host(`erp.dev.in`))
        traefik.http.routers.erp-secure.tls: "true"
        # traefik.http.routers.erp-secure.tls.certresolver: le
        # traefik.http.middlewares.erp_redirect.redirectscheme.scheme: https
        # traefik.http.routers.erp.middlewares: "erp_redirect"
    tty: true
    networks:
      - proxy
      - erp_net
networks:
  proxy:
    external: true
  erp_net:
configs:
   mysql.conf:
     file: './mysql.conf'
   
#   php.ini:
#     file: './docker/php.ini'
#   periodico.conf:
#     file: './docker/supervisor.conf'  

